remote_theme: pmarsceill/just-the-docs
markdown: kramdown
title: CRM-Toolkit
description: Battery-Included CodeIgniter, React, Material-UI Template
logo: images/splash.png
baseurl: /crm-toolkit/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
